version: '3'
services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
  feedback:
    build:
      context: .
      dockerfile: apps/feedback/Dockerfile
    ports:
      - "3001:3001"
  info:
    build:
      context: .
      dockerfile: apps/info/Dockerfile
    ports:
      - "3002:3002"
  pricing:
    build:
      context: .
      dockerfile: apps/pricing/Dockerfile
    ports:
      - "3003:3003"
  projects:
    build:
      context: .
      dockerfile: apps/projects/Dockerfile
    ports:
      - "3004:3004"
  services:
      build:
        context: .
        dockerfile: apps/services/Dockerfile
      ports:
        - "3005:3005"
